name: Format

on: [push, pull_request]

jobs:
  Format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v1

      - name: Install modules
        run: bun install --frozen-lockfile

      - name: Run Format
        run: bun run format
