name: Typecheck

on: [push, pull_request]

jobs:
  Typecheck:
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}

    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v1

      - name: Install modules
        run: bun install

      - name: Run Typecheck
        run: bun run typecheck
